### PR TITLE
Add a new prop to enable scroll to end of a line chart.

### PR DESCRIPTION
**Pull request by rnakhan**
This is helpful in case of a long line chart and the user may be interested in seeing the latest data.

### CODE REVIEW

**Comment by Fischaela** [comment]
Oh, it would be so cool, if you could merge this feature :)

**Comment by trungnguyencmu** [comment]
+1

**Comment by trungnguyencmu** [comment]
can you merge this pr ? please :)

**Comment by oksktank** [comment]
My development PC has been broken and I have not been able to develop this project recently. I'll fix it as soon as possible and merge this feature. Thank you for your contribution.

**Comment by trungnguyencmu** [comment]
@oksktank, Thanks!

**Pull request merged**
